import type { Metadata, Viewport } from 'next';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';

import './globals.css';
import Header from '@/components/layout/Header';

export const metadata: Metadata = {
  title: 'zvt-ui',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ThemeRegistry>
          <Header />
          <div className="my-4 w-container mx-auto">{children}</div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
